### ISSUE TITLE
为什么一会儿就显示断开请刷新？

### ISSUE THREAD

**Issue by wyfang** [walkor/workerman-todpole#13]
大约就5秒钟的样子。

**Comment by wyfang** [comment]
http://wangyifang.com:8383/

**Comment by walkor** [comment]
网址打不开

**Comment by wyfang** [comment]
![image](https://user-images.githubusercontent.com/17900420/40598011-c6e36eaa-6277-11e8-8990-3044db26f202.png)

**Comment by wyfang** [comment]
@walkor 现在可以打开了，帮忙看看？

**Comment by walkor** [comment]
8282 端口连接超时，应该是防火墙或者安全组挡住了8282端口的通讯

**Comment by wyfang** [comment]
@walkor oh,我以为只要8383端口就行。希望教程里要多写上啊，因为服务器正常安全组都是关闭的。
